"
    Copyright (c) 2020 Aucerna. 
    See (MIT) license in root directory.
"

Package { #name : #Kernel,
	#classes : [
		'Array',
		'ArrayedCollection',
		'Association',
		'Behavior',
		'Boolean',
		'CharacterArray',
		'Character',
		'Class',
		'Closure',
		'Collection',
		'CompiledBlock',
		'CompiledMethod',
		'Dictionary',
		'False',
		'HashedCollection',
		'HashTablePolicy',
		'HashTable',
		'Integer',
		'Interval',
		'Magnitude',
		'Metaclass',
		'MethodDictionary',
		'Number',
		'Object',
		'OpenHashTable',
		'OrderedCollection',
		'ProtoObject',
		'SequenceableCollection',
		'Set',
		'SmallInteger',
		'Species',
		'String',
		'Symbol',
		'True',
		'UndefinedObject'
	]
}

